---
# tasks file for mc

- name: "Downloading and setting up {{ mc_app }} on Debian based systems."
  get_url:
    url: "{{ mc_dl_url }}"
    dest: "{{ mc_bin_path }}"
    mode: "{{ mc_bin_permission_mode }}"
