---
# tasks file for mc | EL Family

- name: EL Family | Downloading and setting up {{ mc_app }}
  ansible.builtin.get_url:
    url: "{{ mc_dl_url }}"
    dest: "{{ mc_bin_path }}"
    owner: "{{ mc_file_owner }}"
    group: "{{ mc_file_group }}"
    mode: "{{ mc_file_mode }}"
