---
# tasks file for mc | EL Family

- name: EL Family | Downloading and setting up {{ mc_app }}
  get_url:
    url: "{{ mc_dl_url }}"
    dest: "{{ mc_bin_path }}"
    mode: "{{ mc_bin_permission_mode }}"
